name: Build and Release Launcher

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Pobieranie kodu
        uses: actions/checkout@v4

      - name: Instalacja środowiska Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalacja pakietów (npm install)
        run: npm install

      - name: Budowanie pliku .exe i publikacja!
        # MAGIA JEST TUTAJ: Dopisek "--publish always" wymusza wrzucenie pliku do zakładki Releases
        run: npm run build -- --publish always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}